import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 text-gray-900`}
      >
        <nav className="bg-white shadow p-4 mb-4">
          <div className="max-w-7xl mx-auto flex gap-6">
            <a href="/" className="font-bold text-lg">Auto Realtor Ideas</a>
            <a href="/new-run" className="text-blue-600 hover:underline">New Run</a>
            <a href="/library" className="text-blue-600 hover:underline">Library</a>
            <a href="/api/status" className="text-gray-500 text-sm mt-1">Status</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
